### ISSUE TITLE
Latest version of the add-on (1.11.2) fails on the rpi4 and won't install on the rpi3

### ISSUE THREAD

**Issue by Lheriss** [mihsu81/addon-theengsgw#36]
Hi,
After installing the latest version of the add-on (1.11.2), it launches, but fails with this log :

[20:01:20] INFO: Creating TheengsGateway configuration...
[20:01:24] INFO: IDENTITIES: {"xxxx":"xxxx==","xxxx":"xxx==","xxxx":"xxxx== "}
[20:01:24] INFO: BINDKEYS: 
[20:01:24] INFO: BLACKLIST: 
[20:01:24] INFO: WHITELIST: 
[20:01:24] INFO: Starting TheengsGateway...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/__main__.py", line 5, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/__init__.py", line 56, in main
    configuration["discovery_filter"].remove("GAEN")
AttributeError: 'str' object has no attribute 'remove'

And it won't install on the rpi3.

Do I have to change anything to the config? Thanks!

**Comment by Lheriss** [comment]
OK, I narrowed the problem to this config line, that used to work with the previous version :

DISCOVERY_FILTER: "[IBEACON,GAEN,MS-CDP,APPLE_CONT,APPLE_CONTAT,APPLE_CONTAT-device,H5055]"

I had to suppress  GAEN,MS-CDP,APPLE_CONT,APPLE_CONTAT,APPLE_CONTAT-device to get it launch without error, but it doesn't seem to detect anything anymore... :

INFO:BLEGateway:Starting BLE scan
INFO:BLEGateway:Connected to MQTT broker
INFO:BLEGateway:Subscribed to home/+/BTtoMQTT/undecoded
INFO:BLEGateway:Sent 0 messages to MQTT
INFO:BLEGateway:Sent 0 messages to MQTT
INFO:BLEGateway:Sent 0 messages to MQTT
INFO:BLEGateway:Sent 0 messages to MQTT
INFO:BLEGateway:Sent 0 messages to MQTT

After reverting to 1.11.0, everything turned back to normal :

20:52:23] INFO: Starting TheengsGateway...
INFO:BLEGateway:Starting BLE scan
INFO:BLEGateway:Connected to MQTT broker
INFO:BLEGateway:Subscribed to home/+/BTtoMQTT/undecoded
INFO:BLEGateway:publishing device `{'id': 'xxxx', 'rssi': -69, 'brand': 'Apple', 'model': 'Apple iPhone/iPad', 'model_id': 'APPLEDEVICE', 'type': 'TRACK', 'track': True, 'unlocked': False}`
INFO:BLEGateway:publishing device `{'name': 'Mi Smart Band 5', 'id': 'xxx', 'rssi': -69, 'brand': 'Xiaomi/Amazfit', 'model': 'Mi Band/Smart Watch', 'model_id': 'MB/SW', 'type': 'BODY', 'track': True, 'device': 'Xiaomi/Amazfit Tracker', 'mac': 'xxx'}`
INFO:BLEGateway:publishing device `{'id': 'xxx', 'rssi': -52, 'brand': 'Apple', 'model': 'Apple iPhone/iPad', 'model_id': 'APPLEDEVICE', 'type': 'TRACK', 'track': True, 'unlocked': False}`
INFO:BLEGateway:publishing device `{'name': 'ATC_ECA77E', 'id': 'xxx', 'rssi': -73, 'brand': 'Xiaomi', 'model': 'TH Sensor', 'model_id': 'LYWSD03MMC/MJWSD05MMC_ATC', 'type': 'THB', 'tempc': 25.5, 'tempf': 77.9, 'hum': 60, 'batt': 72, 'volt': 2.708, 'mac': 'xxx'}`
INFO:BLEGateway:publishing device `{'name': 'ATC_75A6B6', 'id': 'xxx', 'rssi': -53, 'brand': 'Xiaomi', 'model': 'TH Sensor', 'model_id': 'LYWSD03MMC/MJWSD05MMC_ATC', 'type': 'THB', 'tempc': 25.3, 'tempf': 77.54, 'hum': 63, 'batt': 45, 'volt': 2.519, 'mac': 'xxxx'}`
INFO:BLEGateway:Sent 258 messages to MQTT

**Comment by stan-moravec** [comment]
Same problem.
Btw it's caused by https://github.com/theengs/gateway/commit/0c7664ec07a1709fb30f0989642252855d7788eb
The `configuration["discovery_filter"]` is a string, so `.remove()` is non-sense.
After shrinking to just `[IBEACON]` it starts, but doesn't log anything anyway. Connection to MQTT is being reset.

**Comment by mihsu81** [comment]
Ok, I'll update the Add-on when a newer version of TGW is released.

**Comment by stan-moravec** [comment]
Any idea how to get back to 1.11.0 in HAOSS? HA CLI doesn't seem to speak versions for `ha addons` ...

**Comment by mihsu81** [comment]
You'd have to revert to the backup of 1.11.0 if you performed a backup.

**Comment by HoM3r17** [comment]
Hi! Same issue with a Pi 5 here, had to restore my 1.11.0 backup as 1.11.2 refused to start with those discovery filters, and started without them but did not send any message to MQTT broker.

**Comment by 1technophile** [comment]
Could you try to shrink the discovery filter to `[IBEACON]`
![image](https://github.com/user-attachments/assets/b3c3f39c-0a4f-4421-8eaf-287aa62f7e14)

Start the addon and share the logs please.

I saw that @stan-moravec tried it, but I would like to have the associated logs

**Comment by mihsu81** [comment]
The issue has been fixed in https://github.com/mihsu81/addon-theengsgw/releases/tag/v1.11.3.

**Comment by HoM3r17** [comment]
Hi @mihsu81 

Updated to 1.11.3, and still the same error : 

```
[14:00:10] INFO: Creating TheengsGateway configuration...
[14:00:12] INFO: IDENTITIES: 
[14:00:12] INFO: BINDKEYS: 
[14:00:12] INFO: BLACKLIST: 
[14:00:12] INFO: WHITELIST: 
[14:00:12] INFO: Starting TheengsGateway...
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/__main__.py", line 5, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/TheengsGateway/__init__.py", line 56, in main
    configuration["discovery_filter"].remove("GAEN")
AttributeError: 'str' object has no attribute 'remove'
```

Here's my config : 

```
MQTT_HOST: 192.168.1.175
MQTT_USERNAME: MQTT username
MQTT_PASSWORD: MQTT PW
MQTT_PORT: 1883
MQTT_PUB_TOPIC: home/TheengsGateway/BTtoMQTT
MQTT_SUB_TOPIC: home/+/BTtoMQTT/undecoded
MQTT_PRE_TOPIC: home/presence/TheengsGateway
PRESENCE: false
GENERAL_PRESENCE: false
PUBLISH_ALL: true
PUBLISH_ADVDATA: false
BLE: true
SCAN_DUR: 15
TIME_BETWEEN: 15
TRACKER_TIMEOUT: 60
LOG_LEVEL: debug
LWT_TOPIC: home/TheengsGateway/LWT
DISCOVERY: true
DISCOVERY_TOPIC: homeassistant
DISCOVERY_DEVICE_NAME: TheengsGateway_HA
DISCOVERY_FILTER: "[IBEACON,GAEN,MS-CDP,APPLE_CONT,APPLE_CONTAT]"
HASS_DISCOVERY: true
ADAPTER: hci1
SCANNING_MODE: active
TIME_SYNC: "[]"
TIME_FORMAT: false
TLS_INSECURE: false
ENABLE_TLS: false
ENABLE_WEBSOCKET: false
IDENTITIES: ""
BINDKEYS: ""
BLACKLIST: ""
WHITELIST: ""

```

Had to revert back to 1.11.0 to get it to work.

**Comment by mihsu81** [comment]
@HoM3r17 Remove [IBEACON,GAEN,MS-CDP,APPLE_CONT,APPLE_CONTAT] or replace it with [IBEACON]. TGW 1.5.0 has an issue with multiple discovery filters. I'll release an updated Add-on when the issue gets fixed in TGW.

> Same problem. Btw it's caused by [theengs/gateway@0c7664e](https://github.com/theengs/gateway/commit/0c7664ec07a1709fb30f0989642252855d7788eb) The `configuration["discovery_filter"]` is a string, so `.remove()` is non-sense. After shrinking to just `[IBEACON]` it starts, but doesn't log anything anyway. Connection to MQTT is being reset.

@stan-moravec https://github.com/mihsu81/addon-theengsgw/releases/tag/v1.11.3 fixes the issues with BLACKLIST and WHITELIST.

**Comment by Tonio16** [comment]
> The issue has been fixed in https://github.com/mihsu81/addon-theengsgw/releases/tag/v1.11.3.

Nope...

**Comment by DigiH** [comment]
> Btw it's caused by https://github.com/theengs/gateway/commit/0c7664ec07a1709fb30f0989642252855d7788eb
> The configuration["discovery_filter"] is a string, so .remove() is non-sense.

This made and still makes perfect sense with the pip installation or building from source, where configuration["discovery_filter"] is a list of strings

```
"discovery_filter": [
        "IBEACON","GAEN","MS-CDP","APPLE_CONT","APPLE_CONTAT"
    ],
```

Not really being involved in the HA Add-on, or Docker image for that matter. I wasn't aware of this drastic change into one whole string;)

Getting a fix ready for testing so that this clean-up can work properly in all incarnations of Theengs Gateway.
