### ISSUE TITLE
Inkbird - 'dict object' has no attribute 'extprobe'

### ISSUE THREAD

**Issue by holdestmade** [mihsu81/addon-theengsgw#45]
The problem
Inkbird Bluetooth Pool Thermometer IBS-TH2/P01B, connects and works ok but lots of this error in the logs

What version of Home Assistant Core has the issue?
2025.7.0

```

Logger: homeassistant.helpers.template
Source: helpers/template.py:819
First occurred: 10:16:00 am (2 occurrences)
Last logged: 10:16:04 am

Error parsing value: 'dict object' has no attribute 'extprobe' (value: {"manufacturerdata": "140a00000017db6408", "name": "tps", "id": "49:22:05:28:07:2B", "rssi": -50, "brand": "Inkbird", "model": "T(H) Sensor", "model_id": "IBS-TH1/TH2/P01B/ITH-12S", "type": "THB", "cidc": false, "acts": true, "tempc": 25.8, "tempf": 78.44, "batt": 100, "distance": 0.19106446691360568}, template: {{ value_json.extprobe | is_defined }})
```

**Comment by DigiH** [comment]
Hi @holdestmade 

Which version of the Theengs Gateway Add-on are you running? Are there any updates available?

This issue should have been addressed since December 2023, and your IBS-P01B JSON should include `"extprobe":false`.

Also a possible complete uninstall and then re-installing the Add-on should get the latest version of the Theengs Decoder Library with this film included.

Let us know how you get on.

**Comment by holdestmade** [comment]
Hi, I'm on 1.11.5. I reinstalled and it is still the same.

These sensors work ok:
IBS-TH1/TH2/P01B/ITH-12S-batt
IBS-TH1/TH2/P01B/ITH-12S-tempc

These are unknown:
IBS-TH1/TH2/P01B/ITH-12S-extprobe
IBS-TH1/TH2/P01B/ITH-12S-hum

Is this the correct repo for the addon:  https://github.com/mihsu81/addon-theengsgw

EDIT: So, I removed the inkbird integration and the log errors go away, but if I disable the addon and keep the integration, no log errors. Seems they are ok on their own but not both at the same time.
